version: '3'

services:
  funnybot:
    env_file: .env
    image: jrush/businesscardbot
    container_name: businesscardbotcontainer
    build: ./
    ports:
      - 8081:80

networks:
  default:
    driver: bridge
